# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - gemeni-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
volumes:
  gemeni-db:
    driver: local